// src/components/editor/EventEdit.vue
<template>
  <a-form :model="eventData">
    <a-form-item label="ID">
      <a-input-number
        v-model:value="eventData.id"
        :disabled="true"
      />
    </a-form-item>
    <a-form-item label="Type">
      <a-radio-group
        v-model:value="eventData.type"
        @change="save"
      >
        <a-radio-button
          v-for="type in ['construct', 'move', 'rotate', 'fade', 'speed']"
          :key="type"
          :value="type"
        >
          {{ type }}
        </a-radio-button>
      </a-radio-group>
    </a-form-item>
    <a-form-item label="Start time">
      <a-input-number
        v-model:value="eventData.startTime"
        :step="10"
        @change="save"
      />
    </a-form-item>
    <a-form-item label="End time">
      <a-input-number
        v-model:value="eventData.endTime"
        :step="10"
        @change="save"
      />
    </a-form-item>
    <a-form :model="eventData.properties">
      <template v-if="eventData.type === 'construct'">
        <a-form-item label="X">
          <a-input-number
            v-model:value="eventData.properties.x"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Y">
          <a-input-number
            v-model:value="eventData.properties.y"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Angle">
          <a-input-number
            v-model:value="eventData.properties.angle"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Alpha">
          <a-input-number
            v-model:value="eventData.properties.alpha"
            :min="0"
            :max="1"
            :step="0.1"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Speed">
          <a-input-number
            v-model:value="eventData.properties.speed"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
      </template>
      <template v-else-if="eventData.type === 'move'">
        <a-form-item label="X">
          <a-input-number
            v-model:value="eventData.properties.x"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Ease X">
          <ease-select
            v-model:value="eventData.properties.easeX"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Y">
          <a-input-number
            v-model:value="eventData.properties.y"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Ease Y">
          <ease-select
            v-model:value="eventData.properties.easeX"
            @change="save"
          />
        </a-form-item>
      </template>
      <template v-else-if="eventData.type === 'rotate'">
        <a-form-item label="Angle">
          <a-input-number
            v-model:value="eventData.properties.angle"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Ease">
          <ease-select
            v-model:value="eventData.properties.ease"
            @change="save"
          />
        </a-form-item>
      </template>
      <template v-else-if="eventData.type === 'fade'">
        <a-form-item label="Alpha">
          <a-input-number
            v-model:value="eventData.properties.alpha"
            :min="0"
            :max="1"
            :step="0.1"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Ease">
          <ease-select
            v-model:value="eventData.properties.ease"
            @change="save"
          />
        </a-form-item>
      </template>
      <template v-else-if="eventData.type === 'speed'">
        <a-form-item label="Speed">
          <a-input-number
            v-model:value="eventData.properties.speed"
            :step="0.01"
            @change="save"
          />
        </a-form-item>
        <a-form-item label="Ease">
          <ease-select
            v-model:value="eventData.properties.ease"
            @change="save"
          />
        </a-form-item>
      </template>
    </a-form>
  </a-form>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

import EaseSelect from './EaseSelect.vue';

import type { EventData } from '../../player/ChartData';

export default defineComponent({
  name: 'EventEdit',
  components: {
    EaseSelect
  },
  props: {
    data: {
      type: <PropType<EventData>>Object,
      required: true,
    },
  },
  emits: ['edit'],
  data() {
    return {
      eventData: this.data,
    };
  },
  watch: {
    data() {
      this.eventData = this.data;
    },
    'eventData.type'() {
      switch (this.eventData.type) {
        case 'construct':
          this.eventData.properties = {
            x: 0,
            y: 0,
            angle: 0,
            alpha: 1,
            speed: 0.01,
          };
          break;
        case 'move':
          this.eventData.properties = {
            x: 0,
            y: 0,
            easeX: 'linear',
            easeY: 'linear',
          };
          break;
        case 'rotate':
          this.eventData.properties = {
            angle: 0,
            ease: 'linear',
          };
          break;
        case 'fade':
          this.eventData.properties = {
            alpha: 1,
            ease: 'linear',
          };
          break;
        case 'speed':
          this.eventData.properties = {
            speed: 0.01,
            ease: 'linear',
          };
          break;
        default:
          break;
      }
    },
  },
  methods: {
    save() {
      this.$emit('edit', this.eventData);
    },
  },
});
</script>

// src/components/editor/EventEdit.svelte
<script>
  import { _ } from 'svelte-i18n';
  import { Tile } from 'carbon-components-svelte/src/Tile';
  import { Form } from 'carbon-components-svelte/src/Form';
  import { FormGroup } from 'carbon-components-svelte/src/FormGroup';
  import { NumberInput } from 'carbon-components-svelte/src/NumberInput';
  import { RadioButton } from 'carbon-components-svelte/src/RadioButton';
  import { RadioButtonGroup } from 'carbon-components-svelte/src/RadioButtonGroup';
  import { Toggle } from 'carbon-components-svelte/src/Toggle';
  import EaseSelect from './EaseSelect.svelte';
  import { chart, currentLineIndex, currentEventIndex } from '../../store';

  let prevEvent = $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex];

  const fix = async () => {
    if ($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex] !== prevEvent) {
      prevEvent = $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex];
      return;
    }
    switch ($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type) {
      case 'construct':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          x: 0,
          y: 0,
          angle: 0,
          alpha: 1,
          speed: 0.01,
        };
        break;
      case 'move':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          x: 0,
          y: 0,
          easeX: 'linear',
          easeY: 'linear',
        };
        break;
      case 'rotate':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          angle: 0,
          ease: 'linear',
        };
        break;
      case 'fade':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          alpha: 1,
          ease: 'linear',
        };
        break;
      case 'speed':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          speed: 0.01,
          ease: 'jump',
        };
        break;
      case 'notevis':
        $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties = {
          visibility: false,
        };
        break;
      default:
        break;
    }
  };
</script>

<Tile>
  <Form>
    <NumberInput label="ID" value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].id} disabled />
    <FormGroup legendText={$_('type')}>
      <RadioButtonGroup bind:selected={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type} on:change={fix}>
        {#each ['construct', 'move', 'rotate', 'fade', 'speed', 'notevis'] as type}
          <RadioButton value={type} labelText={type} />
        {/each}
      </RadioButtonGroup>
    </FormGroup>
    <NumberInput label={$_('starttime')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].startTime} />
    <NumberInput label={$_('endtime')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].endTime} />
    {#if ['construct', 'move'].includes($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type)}
      <NumberInput label={$_('x')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.x} />
      <NumberInput label={$_('y')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.y} />
    {/if}
    {#if $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type === 'move'}
      <EaseSelect labelText={$_('easex')} bind:selected={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.easeX} />
      <EaseSelect labelText={$_('easey')} bind:selected={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.easeY} />
    {/if}
    {#if $chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type === 'notevis'}
      <Toggle labelText={$_('visibility')} labelA={$_('hide')} labelB={$_('show')} bind:toggled={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.visibility} />
    {/if}
    {#if ['construct', 'rotate'].includes($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type)}
      <NumberInput label={$_('angle')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.angle} />
    {/if}
    {#if ['construct', 'fade'].includes($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type)}
      <NumberInput label={$_('alpha')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.alpha} />
    {/if}
    {#if ['construct', 'speed'].includes($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type)}
      <NumberInput label={$_('speed')} bind:value={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.speed} step={0.001} />
    {/if}
    {#if ['rotate', 'fade', 'speed'].includes($chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].type)}
      <EaseSelect labelText={$_('ease')} bind:selected={$chart.judgeLineList[$currentLineIndex].eventList[$currentEventIndex].properties.ease} />
    {/if}
  </Form>
</Tile>
