// src/components/RawJson.svelte
<script>
  import { onDestroy, onMount } from 'svelte';
  import JSONEditor from 'jsoneditor';
  import 'jsoneditor/dist/jsoneditor.css';
  import { chart } from '../store';

  let container;
  let unsubscribe;

  /** @type{JSONEditor} */
  let editor;

  let flag = 0;

  onMount(() => {
    editor = new JSONEditor(container, {
      mode: 'code',
      modes: ['tree', 'code'],
      onChange: () => {
        try {
          ++flag;
          chart.set(editor.get());
        } catch { /** */ }
      },
    }, $chart);
    unsubscribe = chart.subscribe(chart => {
      if (flag > 0) {
        --flag;
      } else {
        editor.set(chart);
      }
    });
  });

  onDestroy(() => {
    unsubscribe();
    editor.destroy();
  });
</script>

<div style="height: 800px" bind:this={container} />

// src/components/RawJson.vue
<template>
  <div
    ref="editor"
    style="height: 400px;"
  />
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

import JSONEditor, { JSONEditorMode, JSONEditorOptions } from 'jsoneditor';
import 'jsoneditor/dist/jsoneditor.min.css';
import { ChartData } from '../player/ChartData';

export default defineComponent({
  name: 'RawJson',
  props: {
    mode: {
      type: <PropType<JSONEditorMode>>String,
      default: 'code',
    },
    modes: {
      type: <PropType<JSONEditorMode[]>>Array,
      default: ['tree', 'code'],
    },
  },
  data() {
    return {
      editor: <JSONEditor>undefined,
      watchFlag: 0,
    }
  },
  watch: {
    '$store.state.chart'(newChart: ChartData) {
      if (this.watchFlag > 0) {
        --this.watchFlag;
      } else {
        this.editor.set(newChart);
      }
    },
  },
  mounted() {
    const options: JSONEditorOptions = {
      mode: this.mode,
      modes: this.modes,
      onChange: () => {
        try {
          const json = this.editor.get();
          this.$store.setChart(json);
          ++this.watchFlag;
        } catch { /** */ }
      },
    };

    this.editor = new JSONEditor(<HTMLDivElement>this.$refs.editor, options, this.$store.state.chart);
  },
  beforeUnmount() {
    this.editor.destroy();
  },
});
</script>
